### PR TITLE
Dev v0.8.1

### LINKED ISSUE #184: Issues with some of the settings dropdowns
Entering a column for 'Filters column' in settings causes the app to crash and returns the error:
Warning: Error in hasColumn: typeof(columnName) == "character" is not TRUE

Entering more than two values for analysis flag values causes the following warning:
Warning in if (!input$`analysisFlag--values` == "") { :
  the condition has length > 1 and only the first element will be used 
- this warning is present in the CRAN version

### PR DESCRIPTION
**Pull request by pburnsdata**
# Issues
Fix #184 

This is a hardcoded solution - so maybe not ideal but its a step towards fixing the problem more generally.

### CODE REVIEW

File: R/validateSettings.R [hunk 1]
```diff
@@ -39,24 +39,40 @@
...
-
+  
   # Check that all required parameters are not null
   requiredChecks <- getRequiredSettings(chart = chart) %>% purrr::map(checkRequired, settings = settings)
-
+  
   #Check that non-null setting columns are found in the data
   dataKeys <- getSettingsMetadata(charts=chart, filter_expr = .data$column_mapping, cols = "text_key")%>%textKeysToList()
+  
+  # Add filters and group_cols to dataKeys manually as temporary fix - they are no longer True for column_mapping in settingsMetadata
```
Comment (jwildfire) [inline R/validateSettings.R]: I like this fix, but lets automate it to cover all metadata settings where `type=vector` and `column_mapping=true`

Comment (jwildfire) [reply R/validateSettings.R]: Which means we need to change `column_mapping` back to true in settingsMetadata.

Comment (jwildfire) [reply R/validateSettings.R]: This can probably serve as a resolution for #170 if we apply similar logic to fields
