### PR TITLE
Settings ui refactor

### LINKED ISSUE #119: Tweak formatting on Settings page
- Move to a one-column layout with collapsable sections. 
- Make it obvious when something has mouseover details beneath it.

### LINKED ISSUE #144: Default Field level data doesn't work after custom mapping
Measure Values don't autofill when you customize the field level data and then load a fully standard data set.

### Steps to Recreate

1. Open the app, and load/switch to the partial SDTM data set
2. Fill in the needed settings on the settings page & view the chart to make sure it renders as expected
3. On the data tab, change back to the default AdAM data.
4. Change to the settings tab, and note that the measure value fields (Bilirubin, etc) are not filled in (shown below). 

image

### LINKED ISSUE #162: Fix partial match counts in Data Module
image

Partial counts not working in current v0.8.0 dev build  - broken in revised `detectStandard()` code

### PR DESCRIPTION
**Pull request by bzkrouse**
- updates per function refactoring
- Fix #119 
- Fix #144  
- Fix #162

### CODE REVIEW

File: inst/eDISH_app/modules/dataUpload/dataUpload.R [hunk 1]
```diff
@@ -129,9 +131,12 @@ dataUpload <- function(input, output, session){
       partial <- ifelse(standard()$details[[current_standard]]$match == "Partial", TRUE, FALSE) 
       
       if (partial) {
-        partial_cols <- standard()$details[[current_standard]]$matched_columns
+        partial_keys <- standard()$details[[current_standard]]$checks %>% 
+          filter(valid==TRUE) %>%
+          select(text_key) %>% 
+          pull()
```
Comment (jwildfire) [inline inst/eDISH_app/modules/dataUpload/dataUpload.R]: been looking for this function - no more `unlist()` for me.
